### ISSUE TITLE
Additional paper on 2D detection

### ISSUE THREAD

**Issue by Wuziyi616** [lijiaman/awesome-transformer-for-vision#2]
Hello! Thanks for your great work! I think you can add this paper [End-to-End Object Detection with Transformers](https://arxiv.org/pdf/2005.12872.pdf) to the 2D detection category. The DETR proposed in this ECCV'20 paper is also very famous I think. Also, there is an improved version of it called [Deformable DETR](https://arxiv.org/pdf/2010.04159.pdf), which significantly accelerates the training speed of DETR.

**Comment by lijiaman** [comment]
Added. Thanks!
